# Generated by Django 5.2 on 2025-06-08 22:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_annoncecolocproposeur_additional_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncecolcchercheur',
            name='date_habite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='annonceproprietaire',
            name='date_de_disponibilite',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
