# Generated by Django 5.2 on 2025-06-09 18:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_annoncecolcchercheur_date_habite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='annoncecolcchercheur',
            name='preferences',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Musique', 'Musique'), ('Sport', 'Sport'), ('Lecture', 'Lecture'), ('Cuisine', 'Cuisine'), ('Cinema', 'Cinema'), ('Video games', 'Video Games'), ('Casanier', 'Casanier'), ('Aventurier', 'Aventurier'), ('Artiste', 'Artiste'), ('Extraverti', 'Extraverti'), ('Introverti', 'Introverti'), ('Communicatif', 'Communicatif'), ('Solitaire', 'Solitaire'), ('Calme', 'Calme'), ('Sérieux', 'Sérieux'), ('Amical', 'Amical')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
