# Generated by Django 5.2 on 2025-06-09 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_annoncecolcchercheur_preferences'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='lu',
            new_name='is_read',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='contenu',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_envoi',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='message',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.AddField(
            model_name='message',
            name='sender',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('participants', models.ManyToManyField(related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='conversation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='accounts.conversation'),
            preserve_default=False,
        ),
    ]
